spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.0.101:1521/xe?allowMultiQueries=true
#    username: eco_fresh
#    password: eco1505!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@192.168.0.101:1521/xe?allowMultiQueries=true
    username: eco_fresh
    password: eco1505!
    
# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis-config.xml
  
  

logging:
  level:
    jdbc: 
      sqlonly: INFO
      sqltiming: OFF
      resulttesttable: OFF
      audit: OFF
      resultset: OFF
      connectcion: OFF